include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

variables:
  OPT_IN_TEST_NEXT_MINOR: 1
  OPT_IN_TEST_NEXT_MAJOR: 1

composer-lint:
  allow_failure: false

eslint:
  allow_failure: false

cspell:
  allow_failure: false

phpcs:
  allow_failure: false

composer (next minor):
  variables:
    _LENIENT_ALLOW_LIST: depcalc,diff,group_content_menu,s3fs,trash

phpstan:
  allow_failure: false

phpstan (next minor):
  allow_failure: false

phpstan (next major):
  allow_failure: false

phpunit:
  allow_failure: false

phpunit (next minor):
  allow_failure: false

phpunit (next major):
  allow_failure: false
