# Schema for the configuration files of the workspace deploy module.
wse_deploy.settings:
  type: config_object
  label: 'Workspace deploy settings'
  mapping:
    deploy_path:
      type: string
      label: 'Deploy path'
    export_plugin:
      type: string
      label: 'Export plugin ID'
    export_plugin_configuration:
      type: ignore
      label: 'Export plugin configuration'
